[workspace]
members = [
    "kissmp-bridge",
    "kissmp-server",
    "kissmp-master",
    "shared"
]
default-members = [
    "kissmp-bridge",
    "kissmp-server"
]
[workspace.package]
version = "0.6.0"
authors = ["hellbox"]
edition = "2018"